---
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/gmail-cleaner-backend"
    schedule:
      interval: "daily"
      time: "07:00"

  - package-ecosystem: "github-actions"
    directory: "/gmail-cleaner-frontend"
    schedule:
      interval: "weekly"
      day: "sunday"